apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
        - name: contacts
          image: contacts-db-sample:latest
          imagePullPolicy: Never
          env:
            - name: APP_DB_ENGINE
              value: postgres
            - name: POSTGRES_DATABASE_URL
              value: postgresql://postgres:example@postgres-rw:5432/contacts?schema=public
      nodeSelector:
        kubernetes.io/hostname: minikube-m02