apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
        - name: contacts
          image: us-west1-docker.pkg.dev/juancavallotti/eetr-artifacts/contacts-db-sample:latest
          env:
            - name: APP_DB_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: contacts-db-config
                  key: APP_DB_ENGINE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: contacts-db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: contacts-db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: contacts-db-config
                  key: DB_NAME
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: contacts-db-config
                  key: DB_SCHEMA
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: contacts-db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: contacts-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?schema=$(DB_SCHEMA)
