apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contacts-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "contacts-static-ip"
    networking.gke.io/managed-certificates: "contacts-cert"
spec:
  rules:
    - host: contacts.eetr.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contacts
                port:
                  number: 80
