apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-configmap.yaml
  - contacts-service.yaml
  - service.yaml
  - postgres-service.yaml
  - statefulset.yaml
  - deployment.yaml
  - managed-certificate.yaml
  - ingress.yaml
