{{- if .Values.ingress.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ingress.managedCertificateName }}
spec:
  domains:
    - {{ .Values.ingress.host }}
{{- end }}
