apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
spec:
  template:
    spec:
      containers:
        - name: contacts
          imagePullPolicy: Never
          env:
            - name: APP_DB_ENGINE
              value: sqlite
            - name: SQLITE_DATABASE_URL
              value: file:../data/contacts.db
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/prisma/data
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: sqlite-pvc
